### ISSUE TITLE
Add different styles of cards

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/cleandocs-template#13]
In the documentation, we have only 1 type of cards

![image](https://github.com/lmas3009/cleandocs-template/assets/60876387/fa05b659-6ce9-43c8-9163-b2911e469b05)

Try to add more designs related to cards.

**✨✨Raise a PR with the design and code.**

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by lmas3009** [comment]
Yes you can work on this
