### ISSUE TITLE
Add different styles for buttons

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/cleandocs-template#14]
In the documentation, we have only 1 type of buttons

![image](https://github.com/lmas3009/cleandocs-template/assets/60876387/041c23e8-ec0c-440d-b1f5-72daf1dd47fe)

Try to add more designs related to buttons.

**✨✨Raise a PR with the design and code.**

**Comment by krrishexe** [comment]
Sure i would like to add some cool designs to your project :p

**Comment by krrishexe** [comment]
Added more designs related to buttons . please accept the PR if you liked the work
Thankyou.

**Comment by lmas3009** [comment]
merged
