### ISSUE TITLE
Home Page Modification (New Feature)  UI Design

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/cleandocs-template#16]
In the home page of the documentation. Try to design like below 

![image](https://github.com/lmas3009/cleandocs-template/assets/60876387/33939a6b-2368-401e-98a7-e356cf6b5a8d)

Make the changes in this section
![image](https://github.com/lmas3009/cleandocs-template/assets/60876387/90f39db7-2f86-4c8e-8392-4c7cd06d14dc)

make sure not to add the play button and background images.
Take a screenshot of the documentation and add it in the laptop display.

**Comment by lmas3009** [comment]
Here we accept the UI Design Only

**Comment by NereidaRondon** [comment]
Hello, I'm going to give this a go.

**Comment by lmas3009** [comment]
Sure @NereidaRondon
