### ISSUE TITLE
docs.html buttons not visible aligned on mobile

### ISSUE THREAD

**Issue by shriekdj** [lmas3009/cleandocs-template#3]
![Screenshot_20220113_155728](https://user-images.githubusercontent.com/35664193/149562308-a86fc1d0-fe70-4e3c-acd6-01d343ac6a11.jpg)

**Comment by lmas3009** [comment]
Can you align the buttons in column

**Comment by lmas3009** [comment]
And replace this one thing
![image](https://user-images.githubusercontent.com/60876387/149611785-a2d7d67d-978c-4487-b94b-a63d6225d589.png)
replace with 
![image](https://user-images.githubusercontent.com/60876387/149611789-be69d082-d292-4d9d-a84a-d2842416b95f.png)

**Comment by shriekdj** [comment]
already aligned in commit https://github.com/lmas3009/cleandocs-template/pull/1/commits/9b938302bca49d60e5ce94a982f3cb899f7387bc of the pr https://github.com/lmas3009/cleandocs-template/pull/1

**Comment by shriekdj** [comment]
done and updated in the pr again
