### ISSUE TITLE
This Is Only Repo, Not Marked as Public Template

### ISSUE THREAD

**Issue by shriekdj** [lmas3009/cleandocs-template#6]
Mark this Repo as Template in Repo Setting.
Given Below Are Screenshots.
![Screenshot_20220313_154532](https://user-images.githubusercontent.com/35664193/158055010-24db9658-7791-4fd6-b2a4-0a97f8961a27.jpg)

## After Changing It Will Look Like this
![Screenshot_20220313_154704](https://user-images.githubusercontent.com/35664193/158054987-b5bb3326-0677-4908-87cc-3e977d5b20c5.jpg)

**Comment by lmas3009** [comment]
Hi, @shriekdj.
I just made this repo as a template.

Thanks for your contribution
Happy Coding

**Comment by shriekdj** [comment]
om I will Close the issue
