### ISSUE TITLE
Add new feature...

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/cleandocs-template#8]
Feature

✨ add dark mode in the home screen

Note
- try to design the page with color combination
- Try to send screenshots before making pr.

**Comment by shriekdj** [comment]
As i Saw the Homepage It's Some part already like an dark theme so You Should Inform Here Things Like

**Comment by shriekdj** [comment]
I Don't have that much of experience in working with 2 themes simultaneously but will try

**Comment by lmas3009** [comment]
Dark mode added
