### ISSUE TITLE
Create an New "v2" Tag Branch for Releasing the v2 With Responsive Design On Repo

### ISSUE THREAD

**Issue by shriekdj** [lmas3009/cleandocs-template#9]
In My Fork I Released the v2. I Just Want to Update the Release It at here also.
After Your Creating the v2 branch in tag part I Will Send Pull Request to Merge the Tag Branch.

**Comment by shriekdj** [comment]
@lmas3009 are you there

**Comment by lmas3009** [comment]
Sorry for the delay..
I just created a new tag. now you can send a new pull request
